# Generated by Django 4.0.3 on 2022-07-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersubscription_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='sort_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
