# Generated by Django 4.0.3 on 2022-09-21 03:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresetrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='used_or_expired',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='expire_time',
            field=models.DateTimeField(default=users.models.current_time_offset),
        ),
    ]
