repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-case-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--config=./pyproject.toml]
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        exclude: .*/migrations/|snoosdigest/|manage.py
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        exclude: .*/migrations/|snoosdigest/|manage.py
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
