[tool.mypy]
strict = true
warn_return_any = false
disallow_subclassing_any = false
disallow_any_generics = false

[[tool.mypy.overrides]]
module = [
    "django.*",
    "praw.*",
    "rest_framework.*"
]
ignore_missing_imports = true
