[tool.mypy]
strict = true
warn_return_any = false
disallow_subclassing_any = false
disallow_any_generics = false
disallow_untyped_decorators = false
exclude = [
    "snoosdigest/",
    "manage.py",
    "/migrations/"
]

[[tool.mypy.overrides]]
module = [
    "django.*",
    "praw.*",
    "prawcore.*",
    "rest_framework.*",
    "cachetools.*",
    "rest_framework_simplejwt.*"
]
ignore_missing_imports = true

[tool.black]
line-length = 100
skip-string-normalization = true
force-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
skip = ["migrations"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "snoosdigest.settings.test"
python_files = "tests.py test_*.py *_tests.py"
