[tool.mypy]
strict = true
warn_return_any = false
disallow_subclassing_any = false
disallow_any_generics = false
disallow_untyped_decorators = false
exclude = [
    "snoosdigest/",
    "manage.py",
    "/migrations/"
]

[[tool.mypy.overrides]]
module = [
    "django.*",
    "praw.*",
    "prawcore.*",
    "rest_framework.*",
    "cachetools.*",
    "rest_framework_simplejwt.*"
]
ignore_missing_imports = true

[tool.black]
line-length = 100
skip-string-normalization = true
extend-exclude = '''
/(
  | migrations
)/
'''
