# Generated by Django 4.0.3 on 2022-08-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subreddit_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='update_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subredditpost',
            name='update_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
