# Generated by Django 4.0.3 on 2022-08-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subreddit_update_source_subredditpost_update_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subredditpost',
            constraint=models.UniqueConstraint(fields=('subreddit', 'reddit_id', 'top_day_order'), name='Unique subreddit day posts'),
        ),
    ]
