# Generated by Django 4.0.3 on 2022-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subreddit_inserted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='data_updated_timestamp_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
