# Generated by Django 4.0.3 on 2022-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subreddit_data_updated_timestamp_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='last_viewed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
