# Generated by Django 4.1.7 on 2023-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subreddit_last_viewed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subredditpost',
            name='body_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
