# Generated by Django 4.1.7 on 2023-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subredditpost_body_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredditpost',
            name='body_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
