# Generated by Django 4.1.7 on 2023-02-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subredditpost_body_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subredditpost',
            name='body_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
